@host = http://localhost:3001
###
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "luca",
    "password": "admin"
}

###
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "root",
    "password": "sekret"
}