@host = http://localhost:3001
###
POST {{host}}/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4NTA2YjU0OTI0ZDA3ZTM3OWExNTk4NyIsImlhdCI6MTc1MDEyNjc4NH0.x_lqCyoj4_W0EiB6x7Rwb8hMIG64oOgCzFwq7eRFWUc

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}
